name: Test and Lint
on: [push, pull_request]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Получаем код из репозитория
      - uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Node.js (указываем вашу версию)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: npm ci

      # Шаг 4: Запускаем линтер (ESLint)
      - name: Run ESLint
        run: npx eslint .

      # Шаг 5: Запускаем тесты с покрытием (Jest)
      - name: Run Tests
        run: npm test
        env:
          NODE_OPTIONS: '--experimental-vm-modules'

      # Опционально: Загружаем отчет о покрытии (если используете сервисы типа Coveralls)
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage

      - name: Upload coverage
        uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info  # Путь к файлу